export const ADD_LOCAL_NOTE = "ADD_LOCAL_NOTE";
export const ADD_FIRE_NOTE = "ADD_FIRE_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";
export const EDIT_NOTE = "EDIT_NOTE";
export const ADD_COMMENT = "ADD_COMMENT";
export const TOGGLE_EDITING ="TOGGLE_EDITING";
export const TOGGLE_COMMENTING ="TOGGLE_COMMENTING";
export const SET_OPTION ="SET_OPTION"